name: CI/CD Workflow
on:
 workflow_dispatch:
jobs:
  build_and_publish:
    name: Building docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2

      - name: setup Docker build
        uses: docker/setup-buildx-action@v3.8.0

      - name: login to Docker hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/python-project:latest .

      - name: push docker image to docker hub
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/python-project:latest

  deploy:
    name: deploy to minikube
    runs-on: ubuntu-latest
    needs: build_and_publish
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
      
      - name: setup-minikube
        uses: medyagh/setup-minikube@v0.0.16
        with:
          version: 1.33.0
      
      - name: start minikube      
        run: |
         minikube start
         minikube status

      - name: Apply Kubernetes Configuration
        run: |
          kubectl apply -f deployment.yml

      - name: sleep for 30s
        run: sleep 30s
        shell: bash

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get services
        
     
   
    
    
