name: CI/CD Workflow
on:
 workflow_dispatch:
jobs:
  build_and_publish:
    name: Building docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2

      - name: setup Docker build
        uses: docker/setup-buildx-action@v3.8.0

      - name: login to Docker hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/python-project:latest .

      - name: push docker image to docker hub
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/python-project:latest

  deploy:
    name: deploy to minikube
    runs-on: ubuntu-latest
    needs: build_and_publish
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack curl
          # Install crictl
          curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.32.0/crictl-v1.32.0-linux-amd64.tar.gz
          sudo tar zxvf crictl-v1.32.0-linux-amd64.tar.gz -C /usr/local/bin
          sudo rm -f crictl-v1.32.0-linux-amd64.tar.gz

      - name: Remove conflicting packages
        run: |
          sudo apt-get remove -y containerd containerd.io
          sudo apt-get autoremove -y

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl enable docker
          sudo systemctl start docker

      - name: Verify Docker Installation
        run: |
          docker --version
          sudo systemctl status docker

      - name: Install Go
        run: |
          wget https://go.dev/dl/go1.20.6.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.20.6.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.bashrc
          go version

      - name: Install cri-dockerd
        run: |
          git clone https://github.com/Mirantis/cri-dockerd.git
          cd cri-dockerd
          mkdir bin
          /usr/local/go/bin/go build -o bin/cri-dockerd
          sudo mv bin/cri-dockerd /usr/local/bin/
          wget https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.service
          wget https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.socket
          sudo mv cri-docker.service cri-docker.socket /etc/systemd/system/
          sudo chmod 644 /etc/systemd/system/cri-docker.service /etc/systemd/system/cri-docker.socket
          sudo systemctl daemon-reload
          sudo systemctl enable cri-docker.service
          sudo systemctl start cri-docker.service

      - name: Install Minikube
        run: |
           curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
           chmod +x minikube
           sudo mv minikube /usr/local/bin/

      - name: start minikube      
        run: |
         sudo minikube start --driver=none
         sudo minikube status

      - name: Apply Kubernetes Configuration
        run: |
          kubectl apply -f deployment.yml

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get services
        
     
   
    
    
